# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
use_frameworks!
target 'Eateries' do
    pod 'Alamofire', '~> 4.5'
    pod 'SwiftyJSON', '~> 4.0'
    pod 'AlamofireImage', '~> 3.3'
end

